from __future__ import absolute_import, division, print_function, unicode_literals

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework import routers

# from feed.filters import NewsFilter
from feed.views import HomePageView, SearchNewsPage
from api.views import NewsViewSet

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'news', NewsViewSet, r"news")

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^(?i)search/$', SearchNewsPage.as_view(), name="search"),
    # Simple implementation of Django RESTFUL API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),
]
